name: glider
description: An opinionated Hacker News client.
version: 2.0.0+41
publish_to: none

environment:
  sdk: ">=3.2.0-0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_presentation: ^1.0.0
  clock: ^1.1.1
  collection: any
  dynamic_color: ^1.6.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_bloc: ^8.1.3
  flutter_displaymode: ^0.6.0
  flutter_inappwebview: ^6.0.0-beta.25
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18
  flutter_secure_storage: ^9.0.0
  formz: ^0.6.1
  glider_data:
    path: packages/glider_data
  glider_domain:
    path: packages/glider_domain
  go_router: ^12.0.0
  http: ^1.1.0
  hydrated_bloc: ^9.1.2
  intl: any
  markdown: ^7.1.1
  material_color_utilities: any
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  pub_semver: ^2.1.4
  relative_time: ^4.0.1
  rxdart: ^0.28.0-dev.0
  scrollview_observer: ^1.16.5
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12
  url_launcher: ^6.2.0

dev_dependencies:
  dependency_validator: ^3.2.3
  flutter_launcher_icons: ^0.13.1
  leancode_lint: ^6.0.0
  melos: ^3.1.1

dependency_overrides:
  material_color_utilities: ^0.8.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoSansMono
      fonts:
        - asset: assets/fonts/NotoSansMono-Regular.ttf
