name: glider
description: An opinionated Hacker News client.
publish_to: "none"
version: 1.16.0+35

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  device_info_plus: ^3.2.2
  dio: ^4.0.4
  dio_smart_retry: ^1.2.0
  fluentui_system_icons: ^1.1.162
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_displaymode: ^0.3.2
  flutter_hooks: ^0.18.2+1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_web_browser: ^0.17.0
  flutter_widget_from_html_core: ^0.8.5+1
  freezed_annotation: ^1.1.0
  hooks_riverpod: ^2.0.0-dev.4
  html: ^0.15.0
  html_unescape: ^2.0.0
  implicitly_animated_reorderable_list: ^0.4.2
  intl: ^0.17.0
  jiffy: ^5.0.0
  json_annotation: ^4.4.0
  native_launcher:
    path: packages/native_launcher
  octo_image: ^1.0.1
  share_plus: ^3.1.0
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  string_validator: ^0.3.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.2
  freezed: ^1.1.1
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  ios: true
  web: true
  macos: true
  windows: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#e57373"
  adaptive_icon_foreground: "assets/icon/adaptive_icon.png"
