name: glider_domain
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  compute: ^1.0.2
  equatable: ^2.0.5
  glider_data:
    path: ../glider_data
  html: ^0.15.4
  material_color_utilities: any
  package_info_plus: ^5.0.1
  pub_semver: ^2.1.4
  rxdart: ^0.27.7

dev_dependencies:
  custom_lint: ^0.5.6
  dependency_validator: ^3.2.3
  leancode_lint: ^7.0.0+1
